# Generated by Django 5.2 on 2025-05-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0002_scanhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('returned', 'Returned'), ('scrapped', 'Scrapped')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshop_app.job')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_uses', to='workshop_app.material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('purchase', 'Purchase')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('job_reference', models.CharField(max_length=100)),
                ('operator_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workshop_app.material')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
