# Generated by Django 5.2 on 2025-05-08 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0004_attachmenttype_materialattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialattachment',
            name='attachment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_app.attachmenttype'),
        ),
        migrations.AlterField(
            model_name='materialattachment',
            name='custom_type',
            field=models.CharField(max_length=50),
        ),
    ]
