# Generated by Django 5.2 on 2025-05-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0005_alter_materialattachment_attachment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('purchase', 'Purchase'), ('restock', 'Restock')], max_length=20),
        ),
    ]
