# Generated by Django 5.2 on 2025-05-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0006_materialtransaction_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('setup_time', models.IntegerField(default=0)),
                ('cleanup_time', models.IntegerField(default=0)),
                ('job_reference', models.CharField(max_length=100)),
                ('operator_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('setup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cleanup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='workshop_app.machine')),
            ],
        ),
    ]
