# Generated by Django 5.2 on 2025-05-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0008_job_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_machines', to='workshop_app.job'),
        ),
        migrations.AlterField(
            model_name='staffsettings',
            name='active_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='workshop_app.job'),
        ),
        migrations.AlterField(
            model_name='staffsettings',
            name='personal_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_users', to='workshop_app.job'),
        ),
    ]
