# Generated by Django 5.2 on 2025-05-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0010_add_job_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_general',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_personal',
        ),
        migrations.AddField(
            model_name='job',
            name='project_type',
            field=models.CharField(choices=[('GEN', 'General'), ('PER', 'Personal'), ('JOB', 'Job')], default='JOB', max_length=3),
        ),
    ]
