# Generated by Django 5.2 on 2025-05-09 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0011_remove_job_is_general_remove_job_is_personal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='workshop_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Time Entry',
                'verbose_name_plural': 'Job Time Entries',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['job', 'user', 'start_time'], name='workshop_ap_job_id_dc34fd_idx'), models.Index(fields=['user', 'start_time'], name='workshop_ap_user_id_5b55b4_idx')],
            },
        ),
    ]
